# Generated by Django 5.2.8 on 2025-12-01 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enderecos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_criacao', models.DateTimeField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.cargos')),
                ('id_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enderecos')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.status')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios')),
            ],
            options={
                'db_table': 'contatos',
            },
        ),
    ]
