# Generated by Django 5.2.8 on 2025-12-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=50, null=True)),
                ('situacao', models.IntegerField()),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('situacao', models.IntegerField()),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
    ]
