CREATE SCHEMA PUBLICACOES;

CREATE TABLE ASSUNTO(
  CODIGO INT NOT NULL,
  DESCRICAO VARCHAR(100),
  
  PRIMARY KEY (CODIGO)
);

CREATE TABLE EDITORA(
    CODIGO INT NOT NULL,
    CNPJ CHAR(18) UNIQUE NOT NULL,
    NOME VARCHAR(50),
    
    PRIMARY KEY (CODIGO)
);

CREATE TABLE NACIONALIDADE(
    CODIGO CHAR(3) NOT NULL,
    PAiS VARCHAR(45),
    
    PRIMARY KEY (CODIGO)
);

CREATE TABLE AUTOR(
    CODIGO INT NOT NULL,
    NOME VARCHAR (50),
    PASSAPORTE CHAR(8) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE,
    NACIONALIDADE_CODIGO CHAR(3),
    
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (NACIONALIDADE_CODIGO) REFERENCES NACIONALIDADE(CODIGO)
);

CREATE TABLE LIVRO(
    CODIGO INT NOT NULL,
    ISBN CHAR(13) UNIQUE NOT NULL,
    TITULO VARCHAR(30),
    PRECO DECIMAL(6, 2),
    DATA_LANCAMENTO DATE,
    ASSUNTO_CODIGO INT NOT NULL,
    EDITORA_CODIGO INT NOT NULL,
    
    PRIMARY KEY (CODIGO),
    FOREIGN KEY (ASSUNTO_CODIGO) REFERENCES ASSUNTO(CODIGO),
    FOREIGN KEY (EDITORA_CODIGO) REFERENCES EDITORA(CODIGO)
);

CREATE TABLE AUTOR_LIVRO(
    AUTOR_CODIGO INT NOT NULL,
    LIVRO_CODIGO INT NOT NULL,
    
    PRIMARY KEY (AUTOR_CODIGO, LIVRO_CODIGO),
    FOREIGN KEY (AUTOR_CODIGO) REFERENCES AUTOR(CODIGO),
    FOREIGN KEY (LIVRO_CODIGO) REFERENCES LIVRO(CODIGO)
);
